const sections = [
  {id:'anatomy',name:'Anatomy',desc:'Airway, thorax, neuroanatomy and applied anatomy'},
  {id:'physiology',name:'Physiology',desc:'Respiratory, cardiovascular, renal, neuro and acid-base'},
  {id:'pharmacology',name:'Pharmacology',desc:'Anaesthetic agents, opioids, muscle relaxants and vasoactive drugs'},
  {id:'equipment',name:'Equipment & Monitoring',desc:'Machines, ventilators, airway devices and monitoring'},
  {id:'airway',name:'Airway & Difficult Airway',desc:'Assessment, intubation, extubation and rescue techniques'},
  {id:'regional',name:'Regional Anaesthesia',desc:'Neuraxial, peripheral blocks, LA toxicity and ultrasound'},
  {id:'general',name:'General Anaesthesia',desc:'Induction, maintenance, emergence and complications'},
  {id:'icu',name:'ICU & Critical Care',desc:'Ventilation, sepsis, shock, weaning and organ support'},
  {id:'obstetric',name:'Obstetric Anaesthesia',desc:'Spinal, GA, PPH, pre-eclampsia and maternal emergencies'},
  {id:'paediatric',name:'Paediatric Anaesthesia',desc:'Airway, fluids, ventilation, analgesia and neonatal care'},
  {id:'pain',name:'Pain Medicine',desc:'Acute pain, chronic pain, PCA and multimodal analgesia'},
  {id:'emergency',name:'Emergency & Trauma',desc:'Resuscitation, trauma, burns and peri-arrest care'}
];

const questions = [
 {id:1,s:'physiology',q:'The normal adult functional residual capacity is best described as:',o:['Tidal volume + inspiratory reserve volume','Expiratory reserve volume + residual volume','Inspiratory reserve volume + residual volume','Vital capacity − residual volume'],a:1,e:'FRC is the volume remaining in the lungs at the end of normal expiration: ERV + RV.'},
 {id:2,s:'pharmacology',q:'Which intravenous induction agent is associated with the least cardiovascular depression?',o:['Propofol','Thiopentone','Etomidate','Midazolam'],a:2,e:'Etomidate generally causes less haemodynamic depression than propofol or thiopentone.'},
 {id:3,s:'airway',q:'A high Mallampati class primarily predicts difficulty with:',o:['Mask ventilation','Laryngoscopy/intubation','Cricothyrotomy','Bronchoscopy'],a:1,e:'Mallampati assessment estimates the visibility of oropharyngeal structures and correlates with difficult laryngoscopy.'},
 {id:4,s:'icu',q:'A commonly used initial lung-protective tidal volume target in ARDS is:',o:['10–12 mL/kg predicted body weight','8–10 mL/kg predicted body weight','6 mL/kg predicted body weight','2–3 mL/kg actual body weight'],a:2,e:'Lung-protective ventilation commonly targets about 6 mL/kg predicted body weight, adjusted to airway pressures and gas exchange.'},
 {id:5,s:'regional',q:'The most important early warning sign of local anaesthetic systemic toxicity after an inadvertent intravascular injection is often:',o:['Severe hypertension','Perioral numbness/neurologic symptoms','Polyuria','Jaundice'],a:1,e:'Early CNS symptoms can include circumoral numbness, tinnitus, metallic taste, agitation or seizures.'},
 {id:6,s:'equipment',q:'Capnography primarily measures:',o:['Inspired oxygen concentration','End-tidal carbon dioxide','Arterial oxygen content','Airway resistance only'],a:1,e:'Capnography provides a continuous waveform and numerical estimate of end-tidal CO2.'},
 {id:7,s:'general',q:'Which neuromuscular blocker is classically associated with hyperkalaemia in susceptible patients?',o:['Rocuronium','Vecuronium','Succinylcholine','Cisatracurium'],a:2,e:'Succinylcholine can cause a rapid increase in serum potassium, especially in high-risk conditions with upregulated extrajunctional receptors.'},
 {id:8,s:'obstetric',q:'The preferred route for rapid neuraxial anaesthesia for caesarean delivery in a woman without a functioning epidural is usually:',o:['Intramuscular analgesia','Spinal anaesthesia','Oral NSAID alone','Local infiltration only'],a:1,e:'Single-shot spinal anaesthesia is commonly used for caesarean delivery when neuraxial contraindications are absent.'},
 {id:9,s:'paediatric',q:'Compared with adults, infants have a higher oxygen consumption and:',o:['Lower functional residual capacity relative to oxygen consumption','Higher FRC relative to body size','Lower metabolic rate','Longer safe apnoea time'],a:0,e:'Infants have relatively small FRC and higher oxygen consumption, contributing to rapid desaturation during apnoea.'},
 {id:10,s:'anatomy',q:'The recurrent laryngeal nerve supplies motor innervation to:',o:['Only cricothyroid','Most intrinsic laryngeal muscles','Diaphragm','Tongue'],a:1,e:'The recurrent laryngeal nerve supplies almost all intrinsic laryngeal muscles except cricothyroid.'},
 {id:11,s:'emergency',q:'During adult cardiac arrest, the standard initial epinephrine dose in ACLS is:',o:['0.1 mg IV','0.5 mg IV','1 mg IV/IO','5 mg IV'],a:2,e:'In adult cardiac arrest, epinephrine 1 mg IV/IO is administered at the recommended interval in current resuscitation algorithms.'},
 {id:12,s:'pain',q:'A major advantage of multimodal analgesia is:',o:['Use of only one drug','Analgesia through different mechanisms with opioid-sparing effect','Guaranteed absence of adverse effects','No need for pain assessment'],a:1,e:'Combining agents/techniques acting through different pathways can improve analgesia while reducing opioid exposure.'},
 {id:13,s:'physiology',q:'Normal arterial PaCO2 in a healthy adult is approximately:',o:['10–20 mmHg','25–30 mmHg','35–45 mmHg','55–65 mmHg'],a:2,e:'Normal PaCO2 is approximately 35–45 mmHg.'},
 {id:14,s:'pharmacology',q:'Noradrenaline primarily produces:',o:['Alpha-1 vasoconstriction with some beta-1 activity','Pure beta-2 vasodilation','Pure muscarinic blockade','Dopamine receptor blockade'],a:0,e:'Noradrenaline is mainly an alpha-1 agonist with beta-1 activity, increasing vascular tone and supporting blood pressure.'},
 {id:15,s:'icu',q:'RSBI is calculated as:',o:['VT/f','f/VT','MAP/HR','HR/MAP'],a:1,e:'Rapid shallow breathing index = respiratory frequency divided by tidal volume in litres.'},
 {id:16,s:'equipment',q:'The pressure measured during an end-inspiratory hold in volume-controlled ventilation is most closely related to:',o:['Peak inspiratory pressure only','Plateau pressure','Central venous pressure','Mean arterial pressure'],a:1,e:'An end-inspiratory pause provides plateau pressure, a surrogate for alveolar/static respiratory system pressure.'},
 {id:17,s:'regional',q:'A major advantage of ultrasound guidance for peripheral nerve blocks is:',o:['No need for anatomical knowledge','Direct visualization of relevant anatomy and needle spread','Elimination of all complications','Guaranteed block success'],a:1,e:'Ultrasound helps identify nerves, vessels and needle position and can visualize local anaesthetic spread.'},
 {id:18,s:'obstetric',q:'In severe pre-eclampsia, neuraxial anaesthesia is generally preferred over general anaesthesia when:',o:['There is a contraindication to neuraxial block','Coagulation is acceptable and there is no major airway/respiratory contraindication','The patient has uncontrolled haemorrhage','The patient refuses consent'],a:1,e:'Neuraxial techniques can avoid airway manipulation and hypertensive responses, but coagulation and other contraindications must be assessed.'},
 {id:19,s:'paediatric',q:'A common reason for rapid desaturation during paediatric anaesthesia is:',o:['Low oxygen consumption','High oxygen consumption relative to FRC','Very high FRC','Slow metabolism'],a:1,e:'High metabolic oxygen consumption coupled with relatively low FRC shortens the oxygen reserve during apnoea.'},
 {id:20,s:'general',q:'The earliest common phase of emergence from general anaesthesia involves:',o:['Complete neuromuscular recovery before any airway response','Return of consciousness and protective airway reflexes','Immediate discharge','Permanent amnesia'],a:1,e:'Emergence includes recovery of consciousness and protective airway reflexes, with assessment of ventilation and neuromuscular function.'},
 {id:21,s:'airway',q:'A definitive emergency front-of-neck access procedure is performed when:',o:['Intubation is easy and oxygenation is adequate','Cannot intubate and cannot oxygenate situation persists','The patient is mildly anxious','A routine elective case starts'],a:1,e:'Emergency front-of-neck access is a rescue airway strategy for CICO (cannot intubate, cannot oxygenate).' },
 {id:22,s:'anatomy',q:'The epidural space lies between the:',o:['Pia and arachnoid','Arachnoid and dura','Ligamentum flavum and dura mater','Dura and pia'],a:2,e:'The epidural space is outside the dura mater and is encountered after the ligamentum flavum in a midline approach.'},
 {id:23,s:'pharmacology',q:'Sugammadex reverses steroidal neuromuscular blockade mainly by:',o:['Acetylcholinesterase inhibition','Encapsulation/binding of the relaxant molecule','Blocking sodium channels','Increasing GABA release'],a:1,e:'Sugammadex forms a tight complex with aminosteroid neuromuscular blockers such as rocuronium.'},
 {id:24,s:'icu',q:'A MAP target commonly used as an initial target in septic shock is:',o:['40 mmHg','50 mmHg','65 mmHg','100 mmHg'],a:2,e:'Current sepsis guidance commonly uses an initial MAP target around 65 mmHg, individualized to the patient.'}
];

const state={screen:'home',questions:[],index:0,answers:[],seconds:300,timerId:null,lastResults:null};
const $=id=>document.getElementById(id);
const storageKey='dnbPrepStateV1';
function loadData(){try{return JSON.parse(localStorage.getItem(storageKey))||{attempted:0,correct:0,history:[],schedule:null}}catch{return {attempted:0,correct:0,history:[],schedule:null}}}
function saveData(d){localStorage.setItem(storageKey,JSON.stringify(d));updateStats()}
function updateStats(){const d=loadData();const attempted=d.attempted||0; const correct=d.correct||0; $('statAttempted').textContent=attempted; $('statCorrect').textContent=(attempted?Math.round(correct/attempted*100):0)+'%'; $('statTotal').textContent=questions.length; $('statStreak').textContent=calcStreak(d.history||[])+' days';}
function calcStreak(hist){const set=new Set(hist.map(x=>x.date));let n=0,d=new Date();d.setHours(0,0,0,0);while(set.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function dailyQuestion(){const idx=dayOfYear(new Date())%questions.length;return questions[idx]}
function dayOfYear(d){const start=new Date(d.getFullYear(),0,0);return Math.floor((d-start)/86400000)}
function renderSections(){const search=($('searchInput').value||'').toLowerCase(); $('sectionGrid').innerHTML=sections.filter(x=>x.name.toLowerCase().includes(search)||x.desc.toLowerCase().includes(search)).map(s=>`<button class="section-card card" data-section="${s.id}"><h3>${s.name}</h3><p>${s.desc}</p><p style="margin-top:10px"><b>${questions.filter(q=>q.s===s.id).length}</b> questions</p></button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.section));}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});state.screen=id}
function startQuiz(section){const base=section==='daily'?[dailyQuestion()]:questions.filter(q=>q.s===section);if(!base.length)return;state.questions=shuffle([...base]).slice(0,Math.min(base.length,10));state.index=0;state.answers=[];state.seconds=Math.max(60,state.questions.length*30);clearInterval(state.timerId);state.timerId=setInterval(tick,1000);$('quizTitle').textContent=section==='daily'?'Daily Challenge':sections.find(x=>x.id===section)?.name||'Quiz';showScreen('quizScreen');renderQuestion();}
function startMock(){state.questions=shuffle([...questions]).slice(0,20);state.index=0;state.answers=[];state.seconds=20*30;clearInterval(state.timerId);state.timerId=setInterval(tick,1000);$('quizTitle').textContent='Mock Test';showScreen('quizScreen');renderQuestion();}
function tick(){state.seconds--;renderTimer();if(state.seconds<=0){clearInterval(state.timerId);finishQuiz();}}
function renderTimer(){$('timer').textContent=`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`}
function renderQuestion(){const q=state.questions[state.index];$('questionCounter').textContent=`Question ${state.index+1} of ${state.questions.length}`;$('questionMeta').textContent=sections.find(x=>x.id===q.s)?.name||q.s;$('questionText').textContent=q.q;$('progressBar').style.width=((state.index)/state.questions.length*100)+'%';$('options').innerHTML=q.o.map((o,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('');$('nextBtn').disabled=true;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectOption(Number(b.dataset.i)));renderTimer();}
function selectOption(i){state.answers[state.index]=i;document.querySelectorAll('.option').forEach((b,j)=>b.classList.toggle('selected',i===j));$('nextBtn').disabled=false;}
function next(){if(state.index<state.questions.length-1){state.index++;renderQuestion()}else finishQuiz()}
function finishQuiz(){clearInterval(state.timerId);const ans=state.answers;let score=0;state.questions.forEach((q,i)=>{if(ans[i]===q.a)score++});state.lastResults={score,total:state.questions.length,answers:ans,questions:state.questions};const d=loadData();d.attempted=(d.attempted||0)+state.questions.length;d.correct=(d.correct||0)+score;const today=new Date().toISOString().slice(0,10);d.history=d.history||[];if(!d.history.some(x=>x.date===today))d.history.push({date:today,score,total:state.questions.length});saveData(d);$('resultScore').textContent=`${score}/${state.questions.length}`;$('resultTitle').textContent=score>=state.questions.length*.8?'Excellent performance!':score>=state.questions.length*.6?'Good work — keep practising.':'Keep practising — revise weak areas.';$('resultMessage').textContent=`Accuracy: ${Math.round(score/state.questions.length*100)}%. Review the explanations below.`;showScreen('resultScreen');renderReview(false)}
function renderReview(force){$('reviewList').innerHTML=state.lastResults.questions.map((q,i)=>{const a=state.lastResults.answers[i];const ok=a===q.a;return `<div class="review-item"><h3>Q${i+1}. ${q.q}</h3><div class="review-answer ${ok?'good':'bad'}">Your answer: ${a==null?'Not answered':q.o[a]} ${ok?'✓':'✗'}</div><div class="review-answer"><b>Correct:</b> ${q.o[q.a]}</div><div class="review-answer muted">${q.e}</div></div>`}).join('');}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function enableNotifications(){if(!('Notification' in window)){alert('This browser does not support notifications.');return}const p=await Notification.requestPermission();if(p==='granted'){notify('DNB Anaesthesia Prep','Notifications enabled. Your study reminder is saved locally.');$('notifyBtn').textContent='Notifications enabled';}else alert('Notification permission was not granted.');}
function notify(title,body){if('Notification' in window&&Notification.permission==='granted'){if(navigator.serviceWorker?.controller){navigator.serviceWorker.ready.then(r=>r.showNotification(title,{body,icon:'icons/icon.svg',badge:'icons/icon.svg'})).catch(()=>new Notification(title,{body}))}else{try{new Notification(title,{body})}catch{}}}}
function saveSchedule(){const time=$('scheduleTime').value;const mode=$('scheduleMode').value;if(!time)return;const d=loadData();d.schedule={time,mode};saveData(d);$('scheduleStatus').textContent=`Saved for ${time} every day. Reminder is checked while this PWA is open/in the background.`;checkSchedule(true)}
function checkSchedule(force=false){const d=loadData();if(!d.schedule)return;const now=new Date();const date=now.toISOString().slice(0,10);const key=`dnbNotify_${date}_${d.schedule.time}_${d.schedule.mode}`;if(localStorage.getItem(key)&&!force)return;const [h,m]=d.schedule.time.split(':').map(Number);if(now.getHours()===h&&now.getMinutes()===m){const text=d.schedule.mode==='daily'?'Your daily DNB Anaesthesia question is ready.':'Time for a DNB Anaesthesia mock test.';notify('DNB Anaesthesia Prep',text);localStorage.setItem(key,'1');}}
function loadSchedule(){const s=loadData().schedule;if(!s)return;$('scheduleTime').value=s.time;$('scheduleMode').value=s.mode;$('scheduleStatus').textContent=`Saved for ${s.time} every day.`}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.deferredInstall=e;$('installBtn').classList.remove('hidden');});$('installBtn').onclick=async()=>{if(window.deferredInstall){window.deferredInstall.prompt();window.deferredInstall=null;$('installBtn').classList.add('hidden')}};
$('startDailyBtn').onclick=()=>startQuiz('daily');$('notifyBtn').onclick=enableNotifications;$('saveScheduleBtn').onclick=saveSchedule;$('nextBtn').onclick=next;$('finishBtn').onclick=finishQuiz;$('backHomeBtn').onclick=()=>{clearInterval(state.timerId);showScreen('homeScreen')};$('homeResultBtn').onclick=()=>showScreen('homeScreen');$('reviewBtn').onclick=()=>renderReview(true);$('searchInput').oninput=renderSections;
$('dailyQuestionTitle').textContent='Daily DNB Question';$('dailyQuestionText').textContent=dailyQuestion().q;renderSections();updateStats();loadSchedule();checkSchedule();setInterval(()=>checkSchedule(),30000);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
